Removed unnecessary multiple inheritance of AddressMessenger by InterfaceNIOTransport and Messenger because it throws a NoSuchMethodError runtime error when sendToAddress(InetSocketAddress, JSONObject) is called on an object of type Messenger. This runtime error seems to happen only when compiled with "ant" but not with an IDE. It is unclear why inheriting the exact same method signature from two interfaces will cause the method to disappear at runtime without any compile time warnings or errors. There is nothing in the specification that seems to suggest this is expected behavior:
http://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.4.8.4
http://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.12.4

Making InterfaceNIOTransport extend AddressMessenger seems to fix this
problem. Interestingly, with the previous multiple inheritance,
casting the object to AddressMessenger before invoking sendToAddress
also seems to to suffice to prevent the runtime error.